the second fucking half of the hiragana
ROBOT-IS-CHILL/robot-is-chill pull request #193
Opened 2024-09-16 18:46 UTC by xbox0

```
fixed | U  ZA ZU ZE ZO 
added | NA NI NU NE NO HA HI HU HE HO MA MI MU ME MO YA YU YO RA RI RU RE WA WO   N
```
also renamed hira_- to chiisai.
added all three furigana characters
renamed that complex character to ZIZAN

2024-09-16 18:47 UTC, xbox0 commented
its all ready (i think)

2024-11-09 06:48 UTC, balt-dev commented
you're gonna have to fix the data bc of strict tiling, shouldn't be too hard though?

2024-11-14 16:15 UTC, balt-dev commented
@xbox0 any updates on this?

2024-11-26 18:20 UTC, someone1065 requested changes
I think these are all the fixes needed.

2024-11-26 18:20 UTC, someone1065 commented on data/custom/blokos-sprites.toml
> +text_zizan = {sprite = "zizan", color = [0, 3], tiling = -1}
```suggestion
text_zizan = {sprite = "zizan", color = [0, 3], tiling = "none"}
```

2024-11-26 18:20 UTC, someone1065 commented on data/custom/blokos-sprites.toml
> +hira_tsu = {sprite = "hira_tsu", color = [0, 3], tiling = -1}
```suggestion
hira_tsu = {sprite = "hira_tsu", color = [0, 3], tiling = "none"}
```

2024-11-26 18:20 UTC, someone1065 commented on data/custom/blokos-sprites.toml
> +hira_re = {sprite = "hira_re", color = [0, 3], tiling = -1}
```suggestion
hira_na = {sprite = "hira_na", color = [0, 3], tiling = "none"}

hira_ni = {sprite = "hira_ni", color = [0, 3], tiling = "none"}

hira_ne = {sprite = "hira_ne", color = [0, 3], tiling = "none"}

hira_no = {sprite = "hira_no", color = [0, 3], tiling = "none"}

hira_nu = {sprite = "hira_nu", color = [0, 3], tiling = "none"}

hira_ha = {sprite = "hira_ha", color = [0, 3], tiling = "none"}

hira_hi = {sprite = "hira_hi", color = [0, 3], tiling = "none"}

hira_he = {sprite = "hira_he", color = [0, 3], tiling = "none"}

hira_ho = {sprite = "hira_ho", color = [0, 3], tiling = "none"}

hira_hu = {sprite = "hira_hu", color = [0, 3], tiling = "none"}

hira_ya = {sprite = "hira_ya", color = [0, 3], tiling = "none"}

hira_yo = {sprite = "hira_yo", color = [0, 3], tiling = "none"}

hira_yu = {sprite = "hira_yu", color = [0, 3], tiling = "none"}

hira_ra = {sprite = "hira_ra", color = [0, 3], tiling = "none"}

hira_ri = {sprite = "hira_ri", color = [0, 3], tiling = "none"}

hira_re = {sprite = "hira_re", color = [0, 3], tiling = "none"}
```

2024-11-26 18:20 UTC, someone1065 commented on data/custom/blokos-sprites.toml
> +chiisai = {sprite = "chiisai", color = [0, 3], tiling = -1}
```suggestion
hira_ro = {sprite = "hira_ro", color = [0, 3], tiling = "none"}

hira_ru = {sprite = "hira_ru", color = [0, 3], tiling = "none"}

hira_wa = {sprite = "hira_wa", color = [0, 3], tiling = "none"}

hira_wo = {sprite = "hira_wo", color = [0, 3], tiling = "none"}

hira_n = {sprite = "hira_n", color = [0, 3], tiling = "none"}

furi_ya = {sprite = "furi_ya", color = [0, 3], tiling = "none"}

furi_yo = {sprite = "furi_yo", color = [0, 3], tiling = "none"}

furi_yu = {sprite = "furi_yu", color = [0, 3], tiling = "none"}

chiisai = {sprite = "chiisai", color = [0, 3], tiling = "none"}
```

2024-11-26 18:20 UTC, someone1065 commented on data/custom/blokos-sprites.toml
> +
```suggestion
hira_ba = {sprite = "hira_ba", color = [0, 3], tiling = "none"}

hira_bi = {sprite = "hira_bi", color = [0, 3], tiling = "none"}

hira_be = {sprite = "hira_be", color = [0, 3], tiling = "none"}

hira_bo = {sprite = "hira_bo", color = [0, 3], tiling = "none"}

hira_bu = {sprite = "hira_bu", color = [0, 3], tiling = "none"}

hira_pa = {sprite = "hira_pa", color = [0, 3], tiling = "none"}

hira_pi = {sprite = "hira_pi", color = [0, 3], tiling = "none"}

hira_pe = {sprite = "hira_pe", color = [0, 3], tiling = "none"}

hira_po = {sprite = "hira_po", color = [0, 3], tiling = "none"}

hira_pu = {sprite = "hira_pu", color = [0, 3], tiling = "none"}

```

2024-12-19 12:51 UTC, xbox0 commented
augh i’m not doing this now

2024-12-31 21:52 UTC, balt-dev commented
needs updating to the new system

2025-03-03 02:49 UTC, balt-dev commented
going to close as stale, lmk if you pick this back up

2025-03-03 02:49 UTC, closed without merging